### ISSUE TITLE
Changing `viewFinder*` props doesn't have any effect

### ISSUE THREAD

**Issue by andreyvital** [ideacreation/react-native-barcodescanner#9] opened 2016-02-03 10:54 UTC
As the title already states... I tried to set custom values for `viewFinder*` properties and none of those worked: `viewFinderDrawLaser`, `viewFinderLaserColor`, `viewFinderBorderLength`, `viewFinderBorderWidth`.

**Comment by andreaskeller** [comment] 2016-02-08 11:02
Changes of ReactProp class in react native 0.19 introduced these issues (https://github.com/facebook/react-native/issues/5649). Please update to newest version 1.0.0 which corrects these. Could you close the issue if the problem is solved after the update? Thank you.

**Comment by andreyvital** [comment] 2016-02-08 11:27
Sure @andreaskeller.

**Comment by andreyvital** [comment] 2016-02-09 01:32
Well, it worked partially, @andreaskeller. `viewFinderDrawLaser` still doesn't have any effect.

**Closed as completed** 2016-02-11 17:54 UTC
